language: node_js
node_js:
  - '8'
  - '9'
  - '10'
  - '11'
  - '12'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache:
  npm: false
before_install:
  - npm i -g npm@latest
install:
  - npm ci
