language: node_js
node_js:
  - "6"
  - "7"
  - "8"
  - "9"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - npm i -g npm@latest
install:
  - npm ci